# Generated by Django 6.0.4 on 2026-05-18 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('pontuacao', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de ocorrencia',
                'verbose_name_plural': 'tipos de ocorrencia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_aplicada', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_ocorrencia', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_vinculadas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='core.tipoocorrencia')),
            ],
            options={
                'verbose_name': 'ocorrencia vinculada',
                'verbose_name_plural': 'ocorrencias vinculadas',
                'ordering': ['-data_ocorrencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsoPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('pontos', models.PositiveIntegerField()),
                ('data_uso', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_pontuacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uso de pontuacao',
                'verbose_name_plural': 'usos de pontuacao',
                'ordering': ['-data_uso', '-criado_em'],
            },
        ),
    ]
